/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class my_hello_Hello */

#ifndef _Included_my_hello_Hello
#define _Included_my_hello_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     my_hello_Hello
 * Method:    say
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_my_hello_Hello_say(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
